- hosts: VPS
  tasks:
    - name: Create Dir
      file:
        path: ~/ansibledir
        state: directory
        mode: '0755'
    - name: Create File
      file:
        path: ~/ansibledir/ansiblefile
        state: touch

- hosts: VMs
  tasks:
    - name: pinging
      ansible.builtin.ping:

